@startuml parkingService
title Parking Service class Diagram

class Vechicle {
  ticketCreatedAt: Date,
  ticketId: Number
}

class Garage {
  MaxCapacity: Number,
  CurrentCapacity: Number,
  Rate: Number,
  CheckIn:(),
  CheckOut:(),
  Payment:(tax: Number, type: String, time: Date): price,
  OpenGate:(payment: Number): Boolean,
} 

@enduml
