@startuml parkingService
title Parking Service class Diagram

class Vechicle {
  type: String,
  ticket: Date,
}

class Garage {
  MaxCapacity: Number,
  CurrentCapacity: Number,
  Rate: Number,
  CheckIn,
  CheckOut,
  Payment:(tax: Number, type: String, time: Date): price,
  OpenGate:(payment: Number): Boolean,
} 



@enduml
